"""Initial migration

Revision ID: 0001
Revises: 
Create Date: 2026-06-27 16:21:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('total_pages_discovered', sa.Integer(), nullable=True),
    sa.Column('total_pages_crawled', sa.Integer(), nullable=True),
    sa.Column('total_pages_failed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('canonical_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'FETCHING', 'FETCHED', 'EXTRACTING', 'EXTRACTED', 'CLASSIFYING', 'CLASSIFIED', 'FAILED', name='pagestatus'), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('render_method', sa.Enum('STATIC', 'PLAYWRIGHT', name='rendermethod'), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_url'), 'pages', ['url'], unique=False)
    op.create_table('page_embeddings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('page_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_embeddings')
    op.drop_index(op.f('ix_pages_url'), table_name='pages')
    op.drop_table('pages')
    op.drop_table('categories')
    op.drop_table('crawl_jobs')
    sa.Enum('DISCOVERED', 'FETCHING', 'FETCHED', 'EXTRACTING', 'EXTRACTED', 'CLASSIFYING', 'CLASSIFIED', 'FAILED', name='pagestatus').drop(op.get_bind())
    sa.Enum('STATIC', 'PLAYWRIGHT', name='rendermethod').drop(op.get_bind())
    sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', name='jobstatus').drop(op.get_bind())
    # ### end Alembic commands ###
