import json
import time

def main():
    with open("makers_nutrition_results.json", "r", encoding="utf-8") as f:
        results = json.load(f)
        
    job_id = results.get("job_id")
    seed_url = results.get("url")
    total_pages = results.get("total_pages")
    categories = results.get("categories", {})
    
    # Group URLs by category and subgroup
    groups = {}
    for cat_name, cat_data in categories.items():
        for page in cat_data.get("pages", []):
            url = page.get("url")
            title = page.get("title", "")
            confidence = page.get("confidence", 0.0)
            method = page.get("classification_method", "")
            
            # Determine sub-group type
            page_type = "Service / Manufacturing Pages"
            if "/blog/" in url:
                page_type = "Blogs"
            elif "/resources/" in url:
                page_type = "Resources"
            elif "/private-label/" in url:
                page_type = "Private Label / Product Pages"
            elif "manufacturer" in url or "manufacturing" in url:
                page_type = "Service / Manufacturing Pages"
            elif "/press/" in url:
                page_type = "Press Releases / News"
            else:
                page_type = "Other / Informational Pages"
                
            groups.setdefault(cat_name, {}).setdefault(page_type, []).append({
                "url": url,
                "title": title,
                "confidence": confidence,
                "method": method
            })
            
    report = []
    report.append("# AI Website Categorization Report: Makers Nutrition")
    report.append(f"**Job ID:** `{job_id}`  ")
    report.append(f"**Seed URL:** {seed_url}  ")
    report.append(f"**Total Categorized Pages:** {total_pages}  ")
    report.append(f"**Generated:** {time.strftime('%Y-%m-%d %H:%M:%S')}  ")
    report.append("\nThis report summarizes the page groupings generated by the AI Categorization prototype. Pages are organized by their main topic/category, and further sub-grouped by their page type (e.g. Service Pages, Blogs, Product Pages).\n")
    
    for category, sub_groups in sorted(groups.items()):
        report.append(f"## Category: **{category}**")
        report.append(f"*(Average Confidence: {categories[category].get('avg_confidence', 0.0):.2%}, Total: {categories[category].get('page_count')} pages)*\n")
        
        for page_type, items in sorted(sub_groups.items()):
            report.append(f"### {page_type}")
            for item in sorted(items, key=lambda x: x["url"]):
                report.append(f"- **{item['title'] or item['url']}**  ")
                report.append(f"  URL: {item['url']}  ")
                report.append(f"  *(Confidence: {item['confidence']:.0%}, via {item['method']} classification)*  ")
            report.append("")
        report.append("---")
        
    with open("makers_nutrition_report.md", "w", encoding="utf-8") as f:
        f.write("\n".join(report))
        
    print("Report generated successfully as makers_nutrition_report.md!")

if __name__ == "__main__":
    main()
